[tool.poetry]
name = "cli"
version = "0.1.0"
description = "CLI утилиты (nl, tail, wc)"
authors = ["Timur Urazov <tu177086@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.3"

[tool.poetry.scripts]
cli = "main:cli"
